### PR TITLE
Add slicer-notebook image

### PR DESCRIPTION
**Pull request by jcfr**
This work was adapted from https://github.com/ihnorton/dockerfiles/tree/master/slicer2binder

Todo: 
* [ ] in addition of `slicer/slicer-notebook:latest`, we should have a proper tag of the form `slicer/slicer-notebook:YYYYMMDD-SHA{7}` like what is done in https://github.com/dockcross/dockcross
* [ ] add script for updating reference in [slicer-notebook/Dockerfile](https://github.com/Slicer/SlicerDocker/blob/0a89b3c071d2771d4802d7b4ce956428210607c5/slicer-notebook/Dockerfile#L71)
* [x] add `slicer-notebook/README.md`
* [x] update to use [jupyter-desktop-server](https://github.com/yuvipanda/jupyter-desktop-server) instead of obsolete [nbnovnc](https://github.com/ryanlovett/nbnovnc)
* [ ] optimize image size

### CODE REVIEW

**Comment by jcfr** [comment]
* Image `slicer/slicer-notebook` is being published and there is currently only the `latest` tag
* The branch associated with this PR https://github.com/Slicer/SlicerNotebooks/pull/5 can be used to test in binder
* when trying to run the notebook, it currently complain with this message `ModuleNotFoundError: No module named 'traitlets'`. After running `pip_install('traitlets')`, it doesn't complain .. but the image associated with view is not rendered

**Comment by jcfr** [comment]
Binder link is now working, here is a screenshot:

image

**Comment by lassoan** [comment]
Remaining issues:
- [x] Traitlets import error
  - a traitlet import was left in JupyterNotebooksLib accidentally, removed it now, updating to latest JupyterNotebooks extension will fix the issue
- [ ] ```ImportError: /home/sliceruser/Slicer-4.11.0-2020-05-11-linux-amd64/lib/Python/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned```
  - workaround: need to force reinstall PIL, using Pillow: `pip_install('--upgrade pillow --force-reinstall')` then restart the kernel
  - It would be better to install Pillow in the docker container.
- [ ] ipycanvas widget does not appear
  - probably we need to install ipycanvas in the jupyter notebook (not in the kernel) ```python3 -m pip install ipycanvas ipyevents```

**Comment by pieper** [comment]
```  ImportError: /home/sliceruser/Slicer-4.11.0-2020-05-11-linux-amd64/lib/Python/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```
I have been getting this same error when using the linux build.  It should probably be split out as its own build issue.

**Comment by lassoan** [comment]
I've managed to fix all the issues (interactive slice viewer works nicely) and even configured desktop vnc access. You can try it here:

https://mybinder.org/v2/gh/lassoan/SlicerNotebooks/use-slicer-notebook-image

I just need to clean things up a bit and then send a pull request.

**Comment by jcfr** [comment]
Thanks, i will do this tomorrow (or may be tonight)

Thanks for your patience 🙏

**Comment by jcfr** [comment]
Re-building image locally for testing.

**Comment by jcfr** [comment]
Going on a :runner: .... will check when build is complete.

**Comment by jcfr** [comment]
Outstanding ! :tada: :pray: :smile: 

After building the latest image, I was able to run the image and connect to the notebook using the following:

```
docker run \
  -p 8888:8888 -p49053:49053 \
  -v /home/jcfr/Projects/SlicerNotebooks:/work  \
  -w /work \
  --rm -ti slicer/slicer-notebook
```

I tried to run the notebook associated with branch [20200515](https://github.com/Slicer/SlicerNotebooks/tree/20200515) and having the prefix `binder-NN-` and they are great :1st_place_medal: Also well done on implementing [JupyterNotebooksLib/display](https://github.com/Slicer/SlicerJupyter/blob/master/JupyterNotebooks/JupyterNotebooksLib/display.py) et al

Todo:

* Before integrating the branch [Slicer/SlicerNotebooks@20200515](https://github.com/Slicer/SlicerNotebooks/tree/20200515), we should probably rename the notebook and remove the prefix `binder` ... indeed they work well when directly running the image like I did.


Few observations (non blocker):

* To avoid passing `-w /work`, we should change the workdir to `/home/sliceruser/nb` .. that would also be consistent with what is done in the Dockerfile from `SlicerNotebooks`

* VNC viewing show two applications when multiple notebooks have been started:

image

* At some point I got an `already used connection message` ... but I am not able to reproduce it yet. I think it was due to the fact I first open `01_Data_Loading_and_Visualization.ipynb` 

* Download progress was not reported  (e.g with `SampleData.SampleDataLogic().downloadCTChest()`)

**Comment by lassoan** [comment]
> Before integrating the branch Slicer/SlicerNotebooks@20200515, we should probably rename the notebook and remove the prefix binder ... indeed they work well when directly running the image like I did.

Notebooks are renamed. We can update the docker image name after the official image is pushed.

> add slicer-notebook/README.md

I have updated the top-level README.md (there was not readme file in the slicer-base folder either but it was documented in the top-level readme).

> To avoid passing -w /work, we should change the workdir to /home/sliceruser/nb .. that would also be consistent with what is done in the Dockerfile from SlicerNotebooks

I'm not sure what you mean, please fix this.

> VNC viewing show two applications when multiple notebooks have been started:

Documented the limitation in JupyterNotebooksLib.AppWindowmethod.

> At some point I got an already used connection message ... but I am not able to reproduce it yet. I think it was due to the fact I first open 01_Data_Loading_and_Visualization.ipynb

Added an issue to track this: https://github.com/Slicer/SlicerJupyter/issues/44. Happens rearely enough so that it is not annoying.

> Download progress was not reported (e.g with SampleData.SampleDataLogic().downloadCTChest())

Progress reporting is implemented in JupyterNotebooksLib.downloadFromURL.

There are a few remaining tasks in the first post (automatic update, reduce image size, etc.). @jcfr if you can resolve those then it's great, if not then you can create bug reports for them.

**Comment by lassoan** [comment]
I'll merge this and create issues for the items that we have not addressed.

**Pull request merged**
